### ISSUE TITLE
"The Loop Keyword" section needs to be updated

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/looping-readme#19]
The section about the Loop keyword is a little inaccurate. It mentions that when you are in the IRB and write and execute an infinite loop, you can exit out of the loop with Control + C. This, however, is not the case.

It is true that when you make an infinite loop in a file and test it out with learn or rspec, you CAN exit out of it with Control + C. However, when you try to do Control + C when there's an infinite loop in the IRB, it doesn't do anything. The only ways to exit out of an infinite loop in an IRB are to refresh the page, log out, or close the page.

Also, as far as I can tell, when the IRB is NOT executing an infinite loop, typing Control + C will simply print the string "^C" in the terminal.

I realize that this is a minor issue, but it may help prevent some confusion in the future if this part of the lesson is updated. Thanks for looking into this!

---Sdcrouse

**Comment by Sdcrouse** [comment]
This is still the case as of 8/6/2018.

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thanks for your feedback 💙

**Comment by Sdcrouse** [comment]
Excellent! That works. Thanks for doing that.

Sdcrouse
