### ISSUE TITLE
Clarity when it comes to order of operations with the assignment operator

### ISSUE THREAD

**Issue by lwadya** [learn-co-curriculum/looping-readme#7]
Just my two cents - feel free to disregard. In my experience teaching Python beginners to the language (mostly those to programming/scripting in general) have some trouble understanding a line of code like this at first glance: age = age + 1. It might be a good idea to clarify exactly what is going on here - namely that everything on the right side of the assignment operator is getting calculated first, so we are reading the value housed in the age variable as it was before the current line of code. It's definitely a simple concept but clarifying that would probably be beneficial to those without prior experience.

**Comment by aviflombaum** [comment]
Addressing this, great feedback, thanks!

**Comment by aviflombaum** [comment]
Closed by e7c661e
