### ISSUE TITLE
Rename and edit lesson to reflect the idea of incrementing vs looping.

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/looping-readme#8]
This is really about how important the idea of incrementing a counter is for the notion of looping at all, which is a great idea. But we should rename the lab and clarify the contents to reflect it. AFAIK this leaves us with no good non-iteration looping readme.

cc @AnnJohn

**Comment by aviflombaum** [comment]
https://github.com/learn-co-curriculum/looping-while-until 
https://github.com/learn-co-curriculum/looping-times 
https://github.com/learn-co-curriculum/looping-loop 
https://github.com/learn-co-curriculum/looping-break-gets

everything i found. will think about what to do...

**Comment by AnnJohn** [comment]
and this one too- https://github.com/learn-co-curriculum/looping-for

**Comment by aviflombaum** [comment]
I re-wrote this lesson. I think it works better. e7c661e
